//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projNational23
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AcademicSSC_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AcademicSSC_Details()
        {
            this.REG_Number = new HashSet<REG_Number>();
        }
        [Key]
        [Display(Name = "SSC Roll Number")]
        [Required]
        public int sscRoll_No { get; set; }

        [Display(Name = "SSC Marks %")]
        [Required]
        public int sscMarks_Percentage { get; set; }

        [Display(Name = "SSC Board")]
        [Required]
        public string sscBoard { get; set; }

        [Display(Name = "Year of Passing")]
        [Required]
        public int sscYear_Of_Passing { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REG_Number> REG_Number { get; set; }
    }
}
