//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projNational23
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AcademicHSC_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AcademicHSC_Details()
        {
            this.REG_Number = new HashSet<REG_Number>();
        }
    [Key]
        [Display(Name = "HSC Rool Number")]
        [Required]
        public int Roll_No { get; set; }
        [Display(Name = "HSC MArks %")]
        [Required]
        public int Marks_Percentage { get; set; }
        [Display(Name = "Specialization")]
        [Required]
        public string Specialization { get; set; }
        [Display(Name = "RBoard")]
        [Required]
        public string Board { get; set; }
        [Display(Name = "Year Of Passing")]
        [Required]
        public int Year_Of_Passing { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REG_Number> REG_Number { get; set; }
    }
}
