//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projNational23
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NationEntities : DbContext
    {
        public NationEntities()
            : base("name=NationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Academic_Details> Academic_Details { get; set; }
        public virtual DbSet<AcademicHSC_Details> AcademicHSC_Details { get; set; }
        public virtual DbSet<AcademicSSC_Details> AcademicSSC_Details { get; set; }
        public virtual DbSet<Admin_Details> Admin_Details { get; set; }
        public virtual DbSet<Applicant_Details> Applicant_Details { get; set; }
        public virtual DbSet<Caste_Details> Caste_Details { get; set; }
        public virtual DbSet<Economic_Backward_Class_Details> Economic_Backward_Class_Details { get; set; }
        public virtual DbSet<Gender_Details> Gender_Details { get; set; }
        public virtual DbSet<Login_Details> Login_Details { get; set; }
        public virtual DbSet<NationalEdu_Details> NationalEdu_Details { get; set; }
        public virtual DbSet<Qualification_Details> Qualification_Details { get; set; }
        public virtual DbSet<REG_Number> REG_Number { get; set; }
        public virtual DbSet<RegScheme_details> RegScheme_details { get; set; }
        public virtual DbSet<Scheme_Details> Scheme_Details { get; set; }
        public virtual DbSet<Files3> Files3 { get; set; }
    
        public virtual int Nat(Nullable<int> matRoll, Nullable<int> matMark, Nullable<int> p8cls)
        {
            var matRollParameter = matRoll.HasValue ?
                new ObjectParameter("MatRoll", matRoll) :
                new ObjectParameter("MatRoll", typeof(int));
    
            var matMarkParameter = matMark.HasValue ?
                new ObjectParameter("MatMark", matMark) :
                new ObjectParameter("MatMark", typeof(int));
    
            var p8clsParameter = p8cls.HasValue ?
                new ObjectParameter("p8cls", p8cls) :
                new ObjectParameter("p8cls", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Nat", matRollParameter, matMarkParameter, p8clsParameter);
        }
    
        public virtual int Nat11(Nullable<int> p11cls, string p11special)
        {
            var p11clsParameter = p11cls.HasValue ?
                new ObjectParameter("p11cls", p11cls) :
                new ObjectParameter("p11cls", typeof(int));
    
            var p11specialParameter = p11special != null ?
                new ObjectParameter("p11special", p11special) :
                new ObjectParameter("p11special", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Nat11", p11clsParameter, p11specialParameter);
        }
    
        public virtual int Nat9(Nullable<int> p9cls)
        {
            var p9clsParameter = p9cls.HasValue ?
                new ObjectParameter("p9cls", p9cls) :
                new ObjectParameter("p9cls", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Nat9", p9clsParameter);
        }
    
        public virtual int Regscheme(Nullable<int> applicant_Id, Nullable<System.DateTime> date_of_apply, string smart_Card_Id, string acc_No, string bank_name, string iFSC_CODE)
        {
            var applicant_IdParameter = applicant_Id.HasValue ?
                new ObjectParameter("Applicant_Id", applicant_Id) :
                new ObjectParameter("Applicant_Id", typeof(int));
    
            var date_of_applyParameter = date_of_apply.HasValue ?
                new ObjectParameter("Date_of_apply", date_of_apply) :
                new ObjectParameter("Date_of_apply", typeof(System.DateTime));
    
            var smart_Card_IdParameter = smart_Card_Id != null ?
                new ObjectParameter("Smart_Card_Id", smart_Card_Id) :
                new ObjectParameter("Smart_Card_Id", typeof(string));
    
            var acc_NoParameter = acc_No != null ?
                new ObjectParameter("Acc_No", acc_No) :
                new ObjectParameter("Acc_No", typeof(string));
    
            var bank_nameParameter = bank_name != null ?
                new ObjectParameter("Bank_name", bank_name) :
                new ObjectParameter("Bank_name", typeof(string));
    
            var iFSC_CODEParameter = iFSC_CODE != null ?
                new ObjectParameter("IFSC_CODE", iFSC_CODE) :
                new ObjectParameter("IFSC_CODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Regscheme", applicant_IdParameter, date_of_applyParameter, smart_Card_IdParameter, acc_NoParameter, bank_nameParameter, iFSC_CODEParameter);
        }
    
        public virtual int RegschemeAD(Nullable<int> admin_Id, string app_status, string payment_Status, Nullable<decimal> funded_amt, Nullable<System.DateTime> fund_transfer_date)
        {
            var admin_IdParameter = admin_Id.HasValue ?
                new ObjectParameter("Admin_Id", admin_Id) :
                new ObjectParameter("Admin_Id", typeof(int));
    
            var app_statusParameter = app_status != null ?
                new ObjectParameter("App_status", app_status) :
                new ObjectParameter("App_status", typeof(string));
    
            var payment_StatusParameter = payment_Status != null ?
                new ObjectParameter("Payment_Status", payment_Status) :
                new ObjectParameter("Payment_Status", typeof(string));
    
            var funded_amtParameter = funded_amt.HasValue ?
                new ObjectParameter("Funded_amt", funded_amt) :
                new ObjectParameter("Funded_amt", typeof(decimal));
    
            var fund_transfer_dateParameter = fund_transfer_date.HasValue ?
                new ObjectParameter("Fund_transfer_date", fund_transfer_date) :
                new ObjectParameter("Fund_transfer_date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RegschemeAD", admin_IdParameter, app_statusParameter, payment_StatusParameter, funded_amtParameter, fund_transfer_dateParameter);
        }
    
        public virtual ObjectResult<adminview_Result> adminview()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<adminview_Result>("adminview");
        }
    
        public virtual int Regdeg(Nullable<int> app_id, string regnum)
        {
            var app_idParameter = app_id.HasValue ?
                new ObjectParameter("App_id", app_id) :
                new ObjectParameter("App_id", typeof(int));
    
            var regnumParameter = regnum != null ?
                new ObjectParameter("regnum", regnum) :
                new ObjectParameter("regnum", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Regdeg", app_idParameter, regnumParameter);
        }
    
        public virtual int Reghsc(Nullable<int> app_id, Nullable<int> rollnum)
        {
            var app_idParameter = app_id.HasValue ?
                new ObjectParameter("App_id", app_id) :
                new ObjectParameter("App_id", typeof(int));
    
            var rollnumParameter = rollnum.HasValue ?
                new ObjectParameter("Rollnum", rollnum) :
                new ObjectParameter("Rollnum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Reghsc", app_idParameter, rollnumParameter);
        }
    
        public virtual int RegNat(Nullable<int> app_id, Nullable<int> nat)
        {
            var app_idParameter = app_id.HasValue ?
                new ObjectParameter("App_id", app_id) :
                new ObjectParameter("App_id", typeof(int));
    
            var natParameter = nat.HasValue ?
                new ObjectParameter("Nat", nat) :
                new ObjectParameter("Nat", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RegNat", app_idParameter, natParameter);
        }
    
        public virtual int Regssc(Nullable<int> app_id, Nullable<int> rollnum)
        {
            var app_idParameter = app_id.HasValue ?
                new ObjectParameter("App_id", app_id) :
                new ObjectParameter("App_id", typeof(int));
    
            var rollnumParameter = rollnum.HasValue ?
                new ObjectParameter("Rollnum", rollnum) :
                new ObjectParameter("Rollnum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Regssc", app_idParameter, rollnumParameter);
        }
    
        public virtual int RegNatt(Nullable<int> app_id, Nullable<int> nat)
        {
            var app_idParameter = app_id.HasValue ?
                new ObjectParameter("App_id", app_id) :
                new ObjectParameter("App_id", typeof(int));
    
            var natParameter = nat.HasValue ?
                new ObjectParameter("Nat", nat) :
                new ObjectParameter("Nat", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RegNatt", app_idParameter, natParameter);
        }
    
        public virtual int Nat111(Nullable<int> natroll, Nullable<int> p11cls, string spec)
        {
            var natrollParameter = natroll.HasValue ?
                new ObjectParameter("natroll", natroll) :
                new ObjectParameter("natroll", typeof(int));
    
            var p11clsParameter = p11cls.HasValue ?
                new ObjectParameter("p11cls", p11cls) :
                new ObjectParameter("p11cls", typeof(int));
    
            var specParameter = spec != null ?
                new ObjectParameter("spec", spec) :
                new ObjectParameter("spec", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Nat111", natrollParameter, p11clsParameter, specParameter);
        }
    
        public virtual int Nat99(Nullable<int> natroll, Nullable<int> p9cls)
        {
            var natrollParameter = natroll.HasValue ?
                new ObjectParameter("natroll", natroll) :
                new ObjectParameter("natroll", typeof(int));
    
            var p9clsParameter = p9cls.HasValue ?
                new ObjectParameter("p9cls", p9cls) :
                new ObjectParameter("p9cls", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Nat99", natrollParameter, p9clsParameter);
        }
    
        public virtual ObjectResult<verifiedapp_Result> verifiedapp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<verifiedapp_Result>("verifiedapp");
        }
    
        public virtual ObjectResult<viewapp_Result> viewapp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewapp_Result>("viewapp");
        }
    
        public virtual ObjectResult<viewappl_Result> viewappl()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewappl_Result>("viewappl");
        }
    
        public virtual ObjectResult<verifiedappl_Result> verifiedappl()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<verifiedappl_Result>("verifiedappl");
        }
    
        public virtual int Regschstud(Nullable<int> appId, string appStatus, string paymentStatus, Nullable<decimal> fundedamt)
        {
            var appIdParameter = appId.HasValue ?
                new ObjectParameter("AppId", appId) :
                new ObjectParameter("AppId", typeof(int));
    
            var appStatusParameter = appStatus != null ?
                new ObjectParameter("AppStatus", appStatus) :
                new ObjectParameter("AppStatus", typeof(string));
    
            var paymentStatusParameter = paymentStatus != null ?
                new ObjectParameter("PaymentStatus", paymentStatus) :
                new ObjectParameter("PaymentStatus", typeof(string));
    
            var fundedamtParameter = fundedamt.HasValue ?
                new ObjectParameter("Fundedamt", fundedamt) :
                new ObjectParameter("Fundedamt", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Regschstud", appIdParameter, appStatusParameter, paymentStatusParameter, fundedamtParameter);
        }
    
        public virtual int Regschadminn(Nullable<int> appId, string appStatus, string paymentStatus, Nullable<decimal> fundedamt, Nullable<System.DateTime> funddate)
        {
            var appIdParameter = appId.HasValue ?
                new ObjectParameter("AppId", appId) :
                new ObjectParameter("AppId", typeof(int));
    
            var appStatusParameter = appStatus != null ?
                new ObjectParameter("AppStatus", appStatus) :
                new ObjectParameter("AppStatus", typeof(string));
    
            var paymentStatusParameter = paymentStatus != null ?
                new ObjectParameter("PaymentStatus", paymentStatus) :
                new ObjectParameter("PaymentStatus", typeof(string));
    
            var fundedamtParameter = fundedamt.HasValue ?
                new ObjectParameter("Fundedamt", fundedamt) :
                new ObjectParameter("Fundedamt", typeof(decimal));
    
            var funddateParameter = funddate.HasValue ?
                new ObjectParameter("Funddate", funddate) :
                new ObjectParameter("Funddate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Regschadminn", appIdParameter, appStatusParameter, paymentStatusParameter, fundedamtParameter, funddateParameter);
        }
    
        public virtual int RegSchAdRej(Nullable<int> appId, string appStatus)
        {
            var appIdParameter = appId.HasValue ?
                new ObjectParameter("AppId", appId) :
                new ObjectParameter("AppId", typeof(int));
    
            var appStatusParameter = appStatus != null ?
                new ObjectParameter("AppStatus", appStatus) :
                new ObjectParameter("AppStatus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RegSchAdRej", appIdParameter, appStatusParameter);
        }
    }
}
