//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projNational23
{
    using System;
    using System.Collections.Generic;
    
    public partial class NationalEdu_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NationalEdu_Details()
        {
            this.REG_Number = new HashSet<REG_Number>();
        }
    
        public int MAT_SAT_Rollno { get; set; }
        public Nullable<int> MAT_SAT_Score { get; set; }
        public Nullable<int> Eighth_class_per { get; set; }
        public Nullable<int> Nineth_class_per { get; set; }
        public Nullable<int> Eleventh_class_per { get; set; }
        public string Eleventh_specialization { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REG_Number> REG_Number { get; set; }
    }
}
