//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projNational23
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegScheme_details
    {
        public int Applicant_ID { get; set; }
        public Nullable<int> Admin_Id { get; set; }
        public System.DateTime Date_of_apply { get; set; }
        public string Smart_Card_Id { get; set; }
        public string App_status { get; set; }
        public string Acc_No { get; set; }
        public string Bank_name { get; set; }
        public string IFSC_CODE { get; set; }
        public string Payment_Status { get; set; }
        public Nullable<decimal> Funded_amt { get; set; }
        public Nullable<System.DateTime> Fund_transfer_date { get; set; }
    
        public virtual Admin_Details Admin_Details { get; set; }
        public virtual Applicant_Details Applicant_Details { get; set; }
    }
}
