//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projNational23
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scheme_Details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Scheme_Details()
        {
            this.Applicant_Details = new HashSet<Applicant_Details>();
        }
    
        public int Scheme_Id { get; set; }
        public string Scheme_Type { get; set; }
        public string Scheme_Name { get; set; }
        public decimal Scholarship_Amount { get; set; }
        public int Age_Criteria { get; set; }
        public int Marks_Criteria { get; set; }
        public Nullable<int> Caste { get; set; }
        public decimal Annual_Income { get; set; }
        public Nullable<int> Qualification_Criteria { get; set; }
        public int Economically_Backward_Classes { get; set; }
        public Nullable<int> Gender_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Applicant_Details> Applicant_Details { get; set; }
        public virtual Caste_Details Caste_Details { get; set; }
        public virtual Economic_Backward_Class_Details Economic_Backward_Class_Details { get; set; }
        public virtual Gender_Details Gender_Details { get; set; }
        public virtual Qualification_Details Qualification_Details { get; set; }
    }
}
